[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn main:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "ON_FAILURE"
maxRetries = 10
