[build]
builder = "NIXPACKS"
buildCommand = """
apt-get update && \
xargs apt-get install -y < apt.txt && \
pip install --upgrade pip && \
pip install -r requirements.txt
"""

[deploy]
startCommand = "gunicorn main:app --bind=0.0.0.0:$PORT --log-file=- --log-level debug --timeout 120 --workers 4"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/health"
interval = "30s"
timeout = "10s"
retries = 3
